[package]
name = "coenobita-middle"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
itertools.workspace = true
coenobita-ast.workspace = true
