[package]
name = "coenobita"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
coenobita-typeck = { path = "crates/coenobita-typeck" }
once_cell = "1.19.0"