[workspace]
members = ["crates/*"]
exclude = ["tests"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
coenobita-ast = { path = "./crates/coenobita-ast" }
coenobita-bin = { path = "./crates/coenobita-bin" }
coenobita-log = { path = "./crates/coenobita-log" }
coenobita-middle = { path = "./crates/coenobita-middle" }
coenobita-parse = { path = "./crates/coenobita-parse" }
coenobita-integrityck = { path = "./crates/coenobita-integrityck" }

itertools = "0.13.0"