[package]
name = "playground"
version = "0.1.0"
edition.workspace = true

[dependencies]
coenobita-middle = { path = "../compiler/coenobita-middle" }



serde.workspace = true
serde_json.workspace = true